{
 "title": "Keycloak Metrics",
 "description": "Monitoring keycloak metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "realm", "label": "Realm", "query": { "query": "label_values(realm)" } },
   { "name": "ClientId", "label": "ClientId", "query": { "query": "label_values(client_id)" } }
  ]
 },
 "panels": [
  {
   "title": "Logins Per REALM",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(realm) (keycloak_logins_total{instance=\"$instance\"})",
     "legendFormat": "{{realm}}"
    }
   ]
  },
  {
   "title": "Logout Per Realm",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(realm) (keycloak_user_event_LOGOUT_total{instance=\"$instance\"})",
     "legendFormat": "{{realm}}"
    }
   ]
  },
  {
   "title": "Total Logged In User",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(sum(keycloak_logins_total{realm=\"paymenthub\", client_id=\"opsapp\"}) or vector(0))\r\n-\r\n(sum(keycloak_user_event_LOGOUT_total{realm=\"paymenthub\"}) or vector(0))\r\n",
     "legendFormat": "{{realm}}"
    }
   ]
  },
  {
   "title": "Logins Per CLIENT",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(keycloak_logins_total{instance=\"$instance\"}) by (client_id)",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Total Logins per REALM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(realm) (increase(keycloak_logins_total{instance=\"$instance\", job=\"keycloak\"}[5m]))",
     "legendFormat": "{{realm}}"
    }
   ]
  },
  {
   "title": "Login Errors on realm $realm",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (realm)(increase(keycloak_failed_login_attempts_total{instance=\"$instance\",job=\"keycloak\" }[5m]))",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Login Attempts per Realm",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (realm)(increase(keycloak_login_attempts_total{instance=\"$instance\",job=\"keycloak\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logins per CLIENT on realm $realm",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (client_id)(increase(keycloak_logins_total{instance=\"$instance\",job=\"keycloak\"}[5m]))",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Login Errors for $ClientId",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (client_id)(increase(keycloak_failed_login_attempts_total{instance=\"$instance\",job=\"keycloak\"}[5m]))\r\n",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Total User Created by Admin",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (realm, resource)(increase(keycloak_admin_event_CREATE_total{instance=\"$instance\",job=\"keycloak\",resource=\"USER\"}[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total User Updated by Admin",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (realm, resource)(increase(keycloak_admin_event_UPDATE_total{instance=\"$instance\",job=\"keycloak\",resource=\"USER\"}[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total User Deleted by Admin",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (realm, resource)(increase(keycloak_admin_event_DELETE_total{instance=\"$instance\",job=\"keycloak\",resource=\"USER\"}[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Memory HEAP",
   "type": "gauge",
   "description": "Memory currently being used by Keycloak.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{instance=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_bytes_max{instance=\"$instance\", area=\"heap\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Memory nonHEAP",
   "type": "gauge",
   "description": "Memory currently being used by Keycloak.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{instance=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_bytes_max{instance=\"$instance\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Process Start Time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "process_start_time_seconds{instance=\"$instance\",job=\"keycloak\"} * 1000",
     "legendFormat": "{{realm}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_max{instance=\"$instance\",job=\"keycloak\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{instance=\"$instance\",job=\"keycloak\"})",
     "legendFormat": "Comitted"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{instance=\"$instance\",job=\"keycloak\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Process CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$instance\",job=\"keycloak\"}[5m])",
     "legendFormat": "Max"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{instance=\"$instance\",job=\"keycloak\"})",
     "legendFormat": "Comitted"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{instance=\"$instance\",job=\"keycloak\"})",
     "legendFormat": "Used"
    }
   ]
  }
 ]
}